rust: Bump nightly compiler to 2026-01-22, Solana CLI to 3.1.8 (#544)
* rust: Bump nightly compiler to 2026-01-22

#### Problem

The nightly compiler hasn't been bumped in a long time.

#### Summary of changes

To go with #543, bump the nightly compiler version. There are a few new
lints to fix:

* the arithmetic side effects lint picks up some tests, so just use
  checked math
* the `struct_extensions` feature on wincode uses some `const` functions
  that aren't stable until 1.85.0, so bump MSRV on solana-message.
  Otherwise we get:

```
error: current MSRV (Minimum Supported Rust Version) is `1.81.0` but this item is stable in a `const` context since `1.83.0`
   --> message/src/lib.rs:119:25
    |
119 |     derive(SchemaWrite, SchemaRead),
    |                         ^^^^^^^^^^ in this derive macro expansion
```

* Also bump Solana CLI

* Update rust-version and frozen-abi digests

* Update more digests